config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/show'
  get 'users/new'
  get 'users/create'
  root to:"memos#index"
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
  post "/create", to:"memos#create"
  get "/show", to:"users#show"
  
  delete "/memos/:id", to:"memos#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
    has_secure_password
    
    has_many :memos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
    before_action :require_user_logged_in, only: [:create]
    before_action :correct_user, only: [:show, :destroy]
    
    def index  #ここにnewも含まれる
        
    end
    
    def create
        Memo.create(what:params["memos"]["memo"],when:params["memos"]["datetime"],wareki:params["memos"]["wareki"],user_id: current_user.id)
        redirect_to "/show" #エラー出そう。個別のshowページに飛ばす方法確認する
    end
    
    def show
      
    end
    
    def destroy
        memo = Memo.find(params["id"])
        memo.destroy
        redirect_to "/show"
    end
    
    def correct_user
        @memo = current_user.memos.find_by(id: params[:id])
        unless @memo
          redirect_to root_url
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  
  def show
    
    #自分のメモだけ持ってくる
    @memos = current_user.memos

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to :login
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
    !   !current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">
    <p>© 2019 warekiseireki-henkan by rika.</p>
    <p>reference → <a href="https://iwb.jp/s/javascript-convert-japanese-calendar-year/">1</a>,
  <a href="https://ja.wikipedia.org/wiki/%E5%85%83%E5%8F%B7%E4%B8%80%E8%A6%A7_(%E6%97%A5%E6%9C%AC)">2</a>
 </p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-left" href="/"><img src="/images/warekiseireki-header.png" alt="warekiseireki-henkan"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
            <li><%= link_to 'もっと変換してみる', root_url %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ユーザーページ<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to '保存したメモを見る', show_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
              </ul>
            </li>
        
      <% else %>
        <li><%= link_to '新規登録', signup_path %></li>
        <li><%= link_to 'ログイン', login_path %></li>
        
      <% end %>
      </ul>
      
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>和暦・西暦変換ツール</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/memos/index.html.erb
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta http-equiv="Content-Script-Type" content="text/javascript" />
</head>

<body>

<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
<div class="center">
<div class="panel panel-default">
  <div class="panel-body">
  
<%= form_tag("/create") do %>
    <div class="form-group">
      
        <%= label_tag "form-title", "変換したい西暦を入力すると、下に表示されます" %>
        <p></p>
        
        <input type="date" id="c" value="1892-05-01" name="memos[datetime]">
        <h2 id="wareki"></h2>
        <input type="hidden" id="a" value="" name="memos[wareki]">
        <p></p>
        
        <%= label_tag "form-title", "メモ" %>
        
        
        <%= text_field :memos, :memo, id:"form-memo", class:"form-control", placeholder:"ex)芥川龍之介の誕生日"%>
        
        <p> </p>
    
    <!--ログイン前後で場合分け -->
    <!-- login機能追加-->
    <% if logged_in? %>
    	<%= submit_tag "保存する", class:"btn btn-success"%>
    <% else %>
    	<%= submit_tag "保存する", class:"btn btn-default"%>
    	<p>※保存には会員登録・ログインが必要です</p>
    <% end %>
<% end %>

</div>
</div>
</div>
</div>
</div>

<script>

var c = document.getElementById('c');
var a = document.getElementById('a');
var wareki = document.getElementById('wareki');
var calc = function() {
  var d = new Date(c.value);
 
  // 和暦の元年のはじまり
  var w = {
    '令和': '2019/05/01',
    '平成': '1989/01/08',
    '昭和': '1926/12/25',
    '大正': '1912/07/30',
    '明治': '1868/01/25',
    '慶応': '1865/05/01',
    '元治': '1864/03/27',
    '文久': '1861/03/29',
    '万延': '1860/04/08',
    '安政': '1855/01/15',
    '嘉永': '1848/04/01',
    '弘化': '1845/01/09',
    '天保': '1831/01/23',
    '文政': '1818/05/26',
    '文化': '1804/03/22',
    '享和': '1801/03/19',
    '寛政': '1789/02/19',
    '天明': '1781/04/25',
    '安永': '1772/12/10',
    '明和': '1764/06/30',
  };
 
  if (d < new Date(w['明和'])) {
    wareki.textContent = 'このサイトでは明和以降を調べることができます。';
  }
  var y = d.getFullYear();
  var r = d.toLocaleDateString('ja-JP-u-ca-japanese');
 
  if (r === 'Invalid Date') {
    wareki.textContent = '変換したい西暦を入力してください';
    return;
  }
  r = r.replace(/^.*?(\d{1,2}).+?$/g, '$1');
  var getDate = function(x, r, d) {
    a.value = x + r + '年' + (d.getMonth() + 1) + '月' + d.getDate() + '日';
    wareki.textContent = x + r + '年' + (d.getMonth() + 1) + '月' + d.getDate() + '日';
  }
  
 
  // 1年は元年と表記
  if (Number(r) === 1) r = '元';
 
  if (d >= new Date(w['令和'])) {
    if (r > 30) r -= 30;
    r = r === 1 ? '元' : r;
    getDate('令和', r, d);
  }
  else if (d >= new Date(w['平成'])) {
    getDate('平成', r, d);
  }
  else if (d >= new Date(w['昭和'])) {
    getDate('昭和', r, d);
  }
  else if (d >= new Date(w['大正'])) {
    getDate('大正', r, d);
  }
  else if (d >= new Date(w['明治'])) {
    getDate('明治', r, d);
  }
  else if (d >= new Date(w['慶応'])) {
    getDate('慶応', r, d);
  }
  else if (d >= new Date(w['元治'])) {
    getDate('元治', r, d);
  }
  else if (d >= new Date(w['文久'])) {
    getDate('文久', r, d);
  }
  else if (d >= new Date(w['万延'])) {
    getDate('万延', r, d);
  }
  else if (d >= new Date(w['安政'])) {
    getDate('安政', r, d);
  }
  else if (d >= new Date(w['嘉永'])) {
    getDate('嘉永', r, d);
  }
  else if (d >= new Date(w['弘化'])) {
    getDate('弘化', r, d);
  }
  else if (d >= new Date(w['天保'])) {
    getDate('天保', r, d);
  }
  else if (d >= new Date(w['文政'])) {
    getDate('文政', r, d);
  }
  else if (d >= new Date(w['文化'])) {
    getDate('文化', r, d);
  }
  else if (d >= new Date(w['享和'])) {
    getDate('享和', r, d);
  }
  else if (d >= new Date(w['寛政'])) {
    getDate('寛政', r, d);
  }
  else if (d >= new Date(w['天明'])) {
    getDate('天明', r, d);
  }
  else if (d >= new Date(w['安永'])) {
    getDate('安永', r, d);
  }
  else if (d >= new Date(w['明和'])) {
    getDate('明和', r, d);
  }
  
}
calc();
 
c.addEventListener('input', function() {
  calc();
});

</script>
</form>
</html>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">新規登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    
<h3>あなたのメモ</h3>
    
    
        <table class="table">
            <thead>
                <tr>
                  <th></th>
                  <th>メモ</th>
                  <th>西暦</th>
                  <th>和暦</th>
                </tr>
            </thead>
        
            
            <tbody>
              <% @memos.each do |memo| %>
                    
                <tr style="table-layout:fixed;">
                 
                    <td><a href="memos/<%=memo.id%>" data-method="delete"><span class="glyphicon glyphicon-trash"></span></a></td>
                    <td style="width:400px;"><%= memo.what%></td>
                    <td style="width:300px;"><%= memo.when%></td>
                    <td style="width:300px;"><%= memo.wareki%></td>
                  
                </tr>
                
            </tbody><% end %>
            
        </table>

</div>